### PR TITLE
update to SyGuS v2

### PR DESCRIPTION
**Pull request by polgreen**
This mega PR is because I ran the batch convert script on all the files in lib and converted them to SyGuS 2

I haven't touched the files outside of lib, I guess it makes sense to preserve the competition benchmarks from each year as v1. I didn't convert the lib-nonconforming files because the convert script doesn't do those. Do you want those converted?

### CODE REVIEW

**Comment by SaswatPadhi** [comment]
Thanks @polgreen!

The translator should work on some of the recent benchmarks I added to `lib-nonconforming/`, but the script won't work on the older benchmarks in `lib-nonconforming/`. The would have to be manually translated at some point. And for the newer I'd have to add a couple of tiny things, e.g. constants of the form `(_ bvW N)`, to the parser.

Also, did you encounter any conversion errors on any of these (the ones in `lib/`)?

**Comment by polgreen** [comment]
I didn't get any reported errors translating the `lib/ `benchmarks, but I am about to run CVC4 on the full set so we could wait until i've done that before merging the PR

**Comment by polgreen** [comment]
So, it takes a long time to run CVC4 on all the benchmarks in the "lib" directory with a 300s timeout on 8 cores.. most of the ones in the new directories e.g., the andrew_lustre dir timeout. But I've got as far as the INV directory and so far none of them error apart from General_plus_10, which I think error'd before (CVC4 doesn't like synth funs that have no arguments, and I think this is a CVC4 problem and not a spec problem). 

I'll let you know when they're all done.

**Comment by SaswatPadhi** [comment]
Sure, no hurry, thanks Elizabeth.I am working on the new CHC benchmarks and on drafting the CHC extension. Ping here whenever you finish running

**Comment by polgreen** [comment]
They finished, all fine apart from the PBE_SLIA dir. I've removed the changes to that dir now

**Comment by SaswatPadhi** [comment]
Thanks @polgreen. Should we keep PBE_SLIA outside the `lib/` for now then, since everything else within `lib/` would now be in v2?

@ajreynol what do you think?

**Comment by ajreynol** [comment]
What's the plan for converting those?  If we are planning to convert PBE_SLIA soon after this PR, it's probably ok to leave them there and make a note that we will change this on a followup PR.

**Comment by SaswatPadhi** [comment]
Thanks @ajreynol. So I think I could do this for now:

1. Merge this PR
2. Create an issue regarding PBE_SLIA so we don't forget about those benchmarks

Thanks again @polgreen for translating all of these!

**Pull request merged**
